-- PARTY 테이블의 PARTY_KEY를 BINARY(16)에서 CHAR(36)으로 변환하는 마이그레이션 스크립트

-- 1단계: 임시 컬럼 생성
ALTER TABLE PARTY ADD COLUMN PARTY_KEY_TEMP CHAR(36) NULL;

-- 2단계: 기존 BINARY(16) 데이터를 CHAR(36) 문자열로 변환
-- MySQL 8.0 이상: BIN_TO_UUID() 함수 사용
-- MySQL 5.7 이하: 수동 변환 필요 (아래 주석 참고)
UPDATE PARTY 
SET PARTY_KEY_TEMP = BIN_TO_UUID(PARTY_KEY)
WHERE PARTY_KEY IS NOT NULL;

-- MySQL 5.7 이하인 경우 위 대신 아래 사용:
-- UPDATE PARTY 
-- SET PARTY_KEY_TEMP = 
--     LOWER(CONCAT(
--         HEX(SUBSTRING(PARTY_KEY, 4, 1)), HEX(SUBSTRING(PARTY_KEY, 3, 1)), 
--         HEX(SUBSTRING(PARTY_KEY, 2, 1)), HEX(SUBSTRING(PARTY_KEY, 1, 1)), '-',
--         HEX(SUBSTRING(PARTY_KEY, 6, 1)), HEX(SUBSTRING(PARTY_KEY, 5, 1)), '-',
--         HEX(SUBSTRING(PARTY_KEY, 8, 1)), HEX(SUBSTRING(PARTY_KEY, 7, 1)), '-',
--         HEX(SUBSTRING(PARTY_KEY, 9, 1)), HEX(SUBSTRING(PARTY_KEY, 10, 1)), '-',
--         HEX(SUBSTRING(PARTY_KEY, 11, 6))
--     ))
-- WHERE PARTY_KEY IS NOT NULL;

-- 3단계: 기존 컬럼 삭제
ALTER TABLE PARTY DROP COLUMN PARTY_KEY;

-- 4단계: 임시 컬럼을 PARTY_KEY로 이름 변경
ALTER TABLE PARTY CHANGE COLUMN PARTY_KEY_TEMP PARTY_KEY CHAR(36) NULL;

-- 5단계: PARTY_MEMBER 테이블도 동일하게 변환
ALTER TABLE PARTY_MEMBER ADD COLUMN PARTY_KEY_TEMP CHAR(36) NULL;

UPDATE PARTY_MEMBER 
SET PARTY_KEY_TEMP = BIN_TO_UUID(PARTY_KEY)
WHERE PARTY_KEY IS NOT NULL;

ALTER TABLE PARTY_MEMBER DROP COLUMN PARTY_KEY;
ALTER TABLE PARTY_MEMBER CHANGE COLUMN PARTY_KEY_TEMP PARTY_KEY CHAR(36) NULL;

-- 6단계: PARTY_WAIT_MEMBER 테이블도 동일하게 변환
ALTER TABLE PARTY_WAIT_MEMBER ADD COLUMN PARTY_KEY_TEMP CHAR(36) NULL;

UPDATE PARTY_WAIT_MEMBER 
SET PARTY_KEY_TEMP = BIN_TO_UUID(PARTY_KEY)
WHERE PARTY_KEY IS NOT NULL;

ALTER TABLE PARTY_WAIT_MEMBER DROP COLUMN PARTY_KEY;
ALTER TABLE PARTY_WAIT_MEMBER CHANGE COLUMN PARTY_KEY_TEMP PARTY_KEY CHAR(36) NULL;

